### ISSUE TITLE
Problem running FCM2 basic example

### ISSUE THREAD

**Issue by jamesb93** [flucoma/FluidCorpusMap2#1]
I get an issue running the README example. Not sure how to prod at it further but thought it might be useful if it is perhaps a meatware issue or maybe specific to ARM64 or something.
[log.txt](https://github.com/flucoma/FluidCorpusMap2/files/7679348/log.txt)

**Comment by g-roma** [comment]
Hello, from the log it would look like the FluCoMa plugins are not installed.

**Comment by jamesb93** [comment]
I have them installed but since recompiling my class library with FluidCorpusMap2 I get the server command error. I remove FCM2 and recompile and everything is back to normal. I'll nuke my setup and start again though.

**Comment by g-roma** [comment]
I don't see any issue related to FCM2 here, so I'd be inclined to close this issue.

**Comment by jamesb93** [comment]
yeah I think it was mostly a bungled environment on my behalf. Sorry.
